language: "rust"
cache: "cargo"
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - |
      if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
        cargo install --force cargo-audit
      fi
  - cargo generate-lockfile
script:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
        cargo audit
      fi
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose
  - cargo test --verbose
if: "type != push OR (tag IS blank AND branch = master)"
